window.COBALT_ROSTER = [
  {
    id: "cobalt-roster-1-2",
    name: "ABACHE,AL JUSTIN, LORENZO",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-3",
    name: "ABELLANO,ANGELO, SILENCIO",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-4",
    name: "ALTAVANO,GEORGE SAEHMIL, BUIZA",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-5",
    name: "ARIMADO,JUNEL, TRAVEZONDA",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-6",
    name: "ATE,SEAN MARK, BELDA",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-7",
    name: "BELEN,KING FRANCIS XAVIER, -",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-8",
    name: "BERMEJO,CARL JUSTINE, ARAÑA",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-9",
    name: "CARIZO,NATANIEL, NOLEAL",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-10",
    name: "COLECHA,JOHN MATTHEW, CARREON",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-11",
    name: "DE LOS SANTOS,AKRAM DHIEYHAV ACE, MANRIQUE",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-12",
    name: "DELOS REYES,RAFAEL, VILGERA",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-13",
    name: "JADIE,AJAY, MORET",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-14",
    name: "LORILLA,KIETH ZYRUS, BELARDO",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-15",
    name: "LOZANO,ARJUN, PANTOJA",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-16",
    name: "MANCERA,CQUIRO ZYUN, -",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-17",
    name: "MIRANDA,MCCARL FRANCIS, LUCIDO",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-18",
    name: "MUSA,JHON AMEIL, CASTILLO",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-19",
    name: "NABO,LYROGE JAMES, SORZA",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-20",
    name: "NACE,RHAY ANN, DEL ROSARIO",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-21",
    name: "PADILLA,GABRIEL LOUIE, -",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-22",
    name: "PADILLA,JOSHA ROBERT, -",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-23",
    name: "SANTANDER,FRANZ KIAN, CARIZO",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-24",
    name: "STA. ANA,MARK ANDREW, BALMEDINA",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-25",
    name: "STA. ANA,WENCY, BELCHEZ",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-26",
    name: "TILA-ON,JOEL JR., SOTELO",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-1-27",
    name: "VIAÑA,JOHN LLOYD, ARTIZUELA",
    gender: "Males",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-2",
    name: "ABEJUELA,KAELA, AGUILAR",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-3",
    name: "AGUILAR,JANESSA KRISTLE, VELASCO",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-4",
    name: "ARIMADO,MARIAN, PRINCIPE",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-5",
    name: "ARIMADO,POLEEN, -",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-6",
    name: "ARINGO,BIANCA, AJERO",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-7",
    name: "ARTIAGA,KRYZEL, MADRONIO",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-8",
    name: "AYLION,NIÑA, MENDIVEL",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-9",
    name: "BARAQUIEL,ANGEL LOREAN, DOCTORA",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-10",
    name: "BERCASIO,ALYANAH, AGUILA",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-11",
    name: "BLANQUISCO,ANGELICA, BEATO",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-12",
    name: "CARIZO,MILKA, CAMPUS",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-13",
    name: "CARIZO,NICA JOY, MARQUEZ",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-14",
    name: "DALIPAYON,MA. JENALYN, PRINCIPE",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-15",
    name: "ESPINAS,JHELLA, PRESAS",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-16",
    name: "GUAPO,LESLY, EBUENGA",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-17",
    name: "MENDENILLA,ASHANTI NANIA, DINOY",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-18",
    name: "MIÑAS,RAISSA JANE, HONA",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-19",
    name: "NACOR,MARY LUISA, ADUCA",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-20",
    name: "NAPAY,JILLIANE, RAVIZ",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-21",
    name: "PEREZ,ANGEL ANN, MENES",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-22",
    name: "TOLEDO,GHECEL, LATIGAY",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
  {
    id: "cobalt-roster-6-23",
    name: "TOLEDO,JAZMINE, ANDES",
    gender: "Females",
    quote: "",
    images: [null, null],
  },
];
